version: '3.3'
services:
    backend:
        build: .
        restart: always
        ports:
            - 8080:8000
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: ambassador
            MYSQL_USER: root_docker
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33066:3306

    redis:
        image: redis
        ports:
            - 6379:6379